### ISSUE TITLE
Terminal tie renders incorrectly at beginning of system [bug]

### ISSUE THREAD

**Issue by mjwalter** [zolaemil/meiView#28]
A note with the attribute `tie="t"`, indicating the "terminal" note in a tied group, normally occurs after a corresponding note with the attribute `tie="i"`, indicating the "initial" note in a tied group. However, when segments of music are displayed, `tie="t"` can appear without a corresponding `tie="i"`.

meiView currently treats such notes as if they began a tied group. Compare the two screenshots of [DC0302](http://duchemin-dev.haverford.edu/piece/DC0302). The following is from the main canvas, which happens to paginate such that the note with `tie="t"` appears at the beginning of the system:

![screen shot 2014-07-29 at 11 35 58](https://cloud.githubusercontent.com/assets/3750681/3737405/ba1afdfe-1736-11e4-9c7d-628c79d36b75.png)

In the phrase view, however, the note and tie are rendered correctly:

![screen shot 2014-07-29 at 11 36 26](https://cloud.githubusercontent.com/assets/3750681/3737416/d22906de-1736-11e4-9b24-e00ea6328071.png)

Note that other ties may be affected by this bug.

A simple solution would be to ignore the tie in such a situation completely. A fuller solution would be to render a short tie before the note. Regardless, a note with `tie="t"` should not have a tie _following_ it.

**Comment by zolaemil** [comment]
Ooops, perhaps staff number isn't accounted for when `tie="i"`s and `tie="t"`s are matched together...

**Comment by zolaemil** [comment]
perhaps they should be anyway, because one should be able to render cross-staff slurs; 

Maybe it is indeed the only solution to check whether the tie="t" note starts after the tie="i" note.

**Comment by mjwalter** [comment]
See the [Guidelines](http://music-encoding.org/documentation/guidelines2013/cmn) on cross-staff slurs:

![screen shot 2014-07-29 at 11 53 57](https://cloud.githubusercontent.com/assets/3750681/3737612/994bbd3c-1738-11e4-9634-7247f57591dc.png)

So perhaps we should not be over-zealous in producing them!

**Comment by zolaemil** [comment]
note that we are dealing with ties here, not slurs.

**Comment by raffazizzi** [comment]
The processing of `@tie` should assume that start and end are on the same staff.  For `@slur` it's different, but as an encoder I would not use it to encode cross-staff and use  `<slur>` with  `@tstamp` and  `@tstamp2` instead. I suggest that MEItoVexFlow should work similarly, e.g. support  `@slur` on the same staff, but require   `<slur>` for cross-staff slurs. (Probably this issue should be mirrored on https://github.com/TEI-Music-SIG/MEItoVexFlow)

**Comment by zolaemil** [comment]
Actually, I think even ties could go cross-staff given that the two staves are played by the same instrument.

**Comment by zolaemil** [comment]
fixed in https://github.com/zolaemil/MEItoVexFlow/commit/ea01b00182395ba54d32b9455fe14695d73cde2d
