### ISSUE TITLE
Note head misplaced

### ISSUE THREAD

**Issue by bencornu** [zolaemil/meiView#38]
Hi,

As you could see below, we have some display problem with notes.

![2015-06-03_145512](https://cloud.githubusercontent.com/assets/11029918/7961166/faf7eb8a-0a05-11e5-8a0f-505bb632fe05.png)

here the xml : 

``` xml
<beam xml:id="m-10b50e4c-1043-4bed-98a4-b98ec794344c">
    <note xml:id="p1cad3n256v1b7s7" dur="8" dur.ges="128p" oct="3" pname="a"/>
    <note xml:id="p1cbd3n384v1b7s7" dur="8" dur.ges="128p" oct="3" pname="b"/>
</beam>
```

![2015-06-03_145542](https://cloud.githubusercontent.com/assets/11029918/7961196/26fc4bae-0a06-11e5-99c8-482d760d90ef.png)
here the xml :

``` xml
<beam xml:id="m-c24ac615-69c0-471b-8b88-edbc0ff3c1e2">
    <note xml:id="p1cbd3n1792v1b23s5" dur="8" dur.ges="128p" oct="3" pname="b"/>
    <note xml:id="p1cad3n1920v1b23s5" dur="8" dur.ges="128p" oct="3" pname="a"/>
</beam>
```

We have tried others combinations but we only have the problem for the couple pname "a/b" and "b/a".

thank you in advance

**Comment by bencornu** [comment]
I updated the meitovexflow with the latest release version (https://github.com/TEI-Music-SIG/MEItoVexFlow/releases/tag/v0.2.0 ) and now it appears to me that the display is ok .

**Comment by zolaemil** [comment]
Thanks for the update! If you create a pull request I can merge it in!

**Comment by RichardFreedman** [comment]
By the way, we have learned that is is mainly the result of some strange behaviors in Sibelius.  You need to check the kinds of beams for notes.

**Comment by zolaemil** [comment]
Good to know, thanks!

2015-06-09 22:11 GMT+01:00 Richard Freedman notifications@github.com:
